### ISSUE TITLE
about pyvisa issue

### ISSUE THREAD

**Issue by jerryjay1225** [bicarlsen/cryocon-22c-controller#1]

**Comment by jerryjay1225** [comment]
Solved by changing backend from @py to c:/windows/system32/visa32.dll

**Comment by bicarlsen** [comment]
This should be solved in v0.0.3, commit https://github.com/bicarlsen/cryocon-22c-controller/commit/a150b29c9ba728cce9631bac8931c9511ab8dfb3.
