### ISSUE TITLE
Problem connecting over ethernet

### ISSUE THREAD

**Issue by arranphipps** [bicarlsen/cryocon-22c-controller#2]
I have my cryocon-22c connected over ethernet. I am unsure how to initialize this device properly using this package. I can use pyvisa to connect to the instrument via

instrument = rm.open_resource("TCPIP::192.168.0.5::5000::SOCKET")

however if I try to pass this as the <port> for cc.CryoconController I get

'TCPIPSocket' object has no attribute 'upper'.

or if I try to pass "TCPIP::192.168.0.5::5000::SOCKET" as the <port> I get

ValueError: Port must start with 'COM' or 'USB'

What is the right way to connect to this over TCPIP/ethernet?

**Comment by bicarlsen** [comment]
Thanks for pointing that out. I believe this is actually an issue with the dependency library [easy_scpi](https://github.com/bicarlsen/easy-scpi) which I also built. I'll try to get it sorted by next week.

**Comment by arranphipps** [comment]
Thanks! 

--
Arran Phipps
Assistant Professor of Physics
California State University - East Bay
25800 Carlos Bee Boulevard
Hayward, CA 94542
***@***.***

**Comment by bicarlsen** [comment]
Just wanted to update you on the status. We're currently using our cryostat for the next few weeks, so I won't be able to test this out until the end of March probably.

In the meantime, if you are able to play with it and find anything else out, please let me know.

Sorry about the delay.

**Comment by bicarlsen** [comment]
Thanks to @mrv96 for [his improvements to the `easy-scpi` library](https://github.com/bicarlsen/easy-scpi/pull/8https://github.com/bicarlsen/easy-scpi/pull/8) I beleive this should be working now. Just be sure to update the `easy-scpi` package to [v0.1.4](https://pypi.org/manage/project/easy-scpi/release/0.1.4/).

**Comment by bicarlsen** [comment]
I'll close this thread due to lack of activity. If anything else comes up, please feel free to open a new issue.
