### ISSUE TITLE
connect problem

### ISSUE THREAD

**Issue by HanYutao2023** [bicarlsen/cryocon-22c-controller#3]
I also have problem when I try connect my cryocon-22c over ethernet. I am unsure how to initialize this device properly using this package. I can use pyvisa to connect to the instrument via

instrument = rm.open_resource("TCPIP::192.168.1.5::5000::SOCKET")

however if I try to pass this as the for cc.CryoconController I get

'Connot find resource: TCPIP::192.168.1.5::5000::SOCKET'

What is the right way to connect to this over TCPIP/ethernet?

**Comment by bicarlsen** [comment]
Unfortunately I no longer have access to this controller, so am unable to test it. But perhaps [this example](https://github.com/bicarlsen/easy-scpi/blob/c209856d4f9115a22ada516a8530cfc7938a0ea0/examples/HMS3010.py#L17) from the underlying [`easy-scpi`](https://github.com/bicarlsen/easy-scpi) package can help.

You can set the `easy_scpi.Instrument.rid` to the resource address.

**Comment by HanYutao2023** [comment]
Thank you very much!

**Comment by bicarlsen** [comment]
Of course :) It seems this solved the issue, so I'll close it, but feel free to reopen it if you are still having issues.
